apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ template "aad-pod-identity.nmi.fullname" . }}-exceptions
  namespace: {{ $.Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict 
    ruleNames:
    - require-drop-all 
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation 
    - autogen-privilege-escalation
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user 
    - autogen-run-as-non-root-user
  - policyName: require-run-as-nonroot 
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - {{ $.Release.Namespace }}
        names:
        - {{ template "aad-pod-identity.nmi.fullname" . }}
