apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "k8s-audit-metrics.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "8000"
    giantswarm.io/monitoring: "true"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    {{- include "k8s-audit-metrics.selectorLabels" . | nindent 4 }}
