apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "k8s-audit-metrics.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      {{- include "k8s-audit-metrics.selectorLabels" . | nindent 6 }}
