{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "k8s-audit-metrics.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name:  {{ tpl .Values.resource.default.name  . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
{{ end }}
