apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "k8s-audit-metrics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    {{- include "k8s-audit-metrics.selectorLabels" . | nindent 4 }}
