project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  registry: docker.io
  name: "giantswarm/k8s-audit-metrics"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 0
  group:
    id: 0
# Resource names are truncated to 47 characters. Kubernetes allows 63 characters
# limit for resource names. When pods for deployments are created they have
# additional 16 characters suffix, e.g. "-957c9d6ff-pkzgw" and we want to have
# room for those suffixes.
#
# NOTE: All values under resource key need to be used with `tpl` to render them
# correctly in the templates. This is because helm doesn't template values.yaml
# file and it has to be a valid json. Example usage:
#
#     {{ tpl .Values.resource.default.name . }}.
#
resource:
  default:
    name: '{{ .Release.Name | replace "." "-" | trunc 47 }}'
    namespace: "kube-system"
  psp:
    name: '{{ .Release.Name | replace "." "-" | trunc 47 }}-psp'

verticalPodAutoscaler:
  enabled: true

# priorityClassName used by the pod.
priorityClassName: "giantswarm-critical"
